name: speeder_website
description: "Digital Marketing Agency"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:

  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
   
  auto_size_text: ^3.0.0
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  easy_debounce: ^2.0.3
  debounce_throttle: ^2.0.0
 
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/phone.png
    - assets/images/youtube.png
    - assets/images/facebook.png
    - assets/images/social_media.png
    - assets/images/instagram.png
    - assets/images/linkedIn.png
    - assets/images/ellipse_1.png
    - assets/images/ellipse_2.png
    - assets/images/person.png
    - assets/images/graph.png
    - assets/images/emojii.png
    - assets/images/progress_indicator.png
    - assets/images/video_play.png
    - assets/images/star.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/images/img6.png
    - assets/images/img7.png
    - assets/images/img8.png
    - assets/images/img9.png
    - assets/fonts/
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png
    - assets/images/10.png
    - assets/images/11.png
    - assets/images/12.png
    - assets/images/13.png
    - assets/images/pc1.png
    - assets/images/pc2.png
    - assets/images/pc3.png
    - assets/images/pc4.png
    - assets/images/pc5.png
    - assets/images/pc6.png
    - assets/images/pc7.png
    - assets/images/pc8.png
    - assets/images/lady.png
    - assets/images/a1.png
    - assets/images/a2.png
    - assets/images/a5.png
    - assets/images/a6.png
    - assets/images/a7.png
    - assets/images/a9.png
    - assets/images/a12.png
    - assets/images/a14.png
    - assets/images/b1.png
    - assets/images/b2.png
    - assets/images/b3.png
    - assets/images/b4.png
    - assets/images/b5.png
    - assets/images/b6.png
    - assets/images/b7.png
    - assets/images/c1.png
    - assets/images/c2.png
    - assets/images/c3.png
    - assets/images/c4.png
    - assets/images/tick.png
    - assets/images/arrow.png

    
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: Montserrat
      fonts:
         - asset: assets/fonts/Montserrat-Black.ttf
         - asset: assets/fonts/Montserrat-BlackItalic.ttf
         - asset: assets/fonts/Montserrat-Bold.ttf
         - asset: assets/fonts/Montserrat-BoldItalic.ttf
         - asset: assets/fonts/Montserrat-ExtraBold.ttf
         - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
         - asset: assets/fonts/Montserrat-ExtraLight.ttf
         - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
         - asset: assets/fonts/Montserrat-Italic.ttf
         - asset: assets/fonts/Montserrat-Light.ttf
         - asset: assets/fonts/Montserrat-LightItalic.ttf
         - asset: assets/fonts/Montserrat-Medium.ttf
         - asset: assets/fonts/Montserrat-MediumItalic.ttf
         - asset: assets/fonts/Montserrat-Regular.ttf
         - asset: assets/fonts/Montserrat-SemiBold.ttf
         - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
         - asset: assets/fonts/Montserrat-Thin.ttf
         - asset: assets/fonts/Montserrat-ThinItalic.ttf
         
         

     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
